#!/usr/bin/env python
from govnsiblecli.modules.base.utils.display import init_logger
from govnsiblecli.modules.base.utils import yaml_handler
from govnsiblecli.modules.base.play_handler import PlayHandler
from govnsiblecli.modules.base.inventory import InventoryBase
from govnsiblecli.modules.executor import scan_executor
logger = init_logger("root")
import argparse


def main():
    parser = argparse.ArgumentParser(description='Playbook executor')
    parser.add_argument('-i', type=str, help='Inventory filepath', required=False)
    parser.add_argument('playbook', type=str, help='Path to playbook file')
    args = parser.parse_args()
    print(args.playbook)
    print(args.i)
    playbook_handler(args.playbook, args.i)


def playbook_handler(playbook_path, inventory_file):
    playbook_content = yaml_handler.load_file(playbook_path)
    inventory = InventoryBase(inventory_file)
    inventory.init_inventory()

    logger.info(f"Current inventory {inventory.groups} ")
    for play in playbook_content:
        executor = "ssh"
        logger.info(play.get('name'))
        play = PlayHandler(play, playbook_path)
        connection_type = play.play_contents.get('connection')
        host_group = play.play_contents.get('host_list')
        if connection_type == 'local' and host_group == 'localhost':
            logger.info('Executing playbook locally')
            executor = 'local'
        play_tasks = play.play_contents.get('tasks')
        print(play_tasks)
        print(scan_executor())
    #
    #
    #     print("Before", play.play_facts)
    #     play.set_facts_from_play()
    #     print("After",play.play_facts)
    # logger.info(playbook_content)

if __name__ == '__main__':
    main()